### ISSUE TITLE
build failure against boost-1.62: error: 'degree' was not declared in this scope

### ISSUE THREAD

**Issue by trofi** [bcgsc/abyss#130]
Build failure on current master looks like that:

```
make[2]: Entering directory '/home/slyfox/dev/git/abyss/Konnector'
g++ -DHAVE_CONFIG_H -I. -I..  -I.. -I../Common -I../DataLayer -I/home/slyfox/dev/git/abyss      -isystem/home/slyfox/dev/git/abyss/boost_1_56_0 -Wall -Wextra -fopenmp -g -O2 -MT konnector-konnector.o -MD -MP -MF .deps/konnector-konnector.Tpo -c -o konnector-konnector.o `test -f 'konnector.cc' || echo './'`konnector.cc
In file included from /usr/include/boost/graph/breadth_first_search.hpp:21:0,
                 from ../Graph/BidirectionalBFS.h:8,
                 from konnector.h:7,
                 from konnector.cc:8:
/usr/include/boost/graph/graph_concepts.hpp: In instantiation of 'boost::concepts::BidirectionalGraph<G>::~BidirectionalGraph() [with G = DBGBloom<BloomFilter>]':
/usr/include/boost/graph/graph_concepts.hpp:114:5:   required from 'static void boost::concepts::requirement<boost::concepts::failed************ Model::************>::failed() [with Model = boost::concepts::BidirectionalGraphConcept<DBGBloom<BloomFilter> >]'
/usr/include/boost/concept_check.hpp:50:7:   required from 'void boost::function_requires(Model*) [with Model = boost::concepts::BidirectionalGraphConcept<DBGBloom<BloomFilter> >]'
../Graph/BidirectionalBFS.h:90:75:   required from 'void bidirectionalBFS(const BidirectionalGraph&, typename boost::graph_traits<Graph>::vertex_descriptor, typename boost::graph_traits<Graph>::vertex_descriptor, Buffer&, Buffer&, BidirectionalBFSVisitor<BidirectionalGraph>&, ColorMap&, ColorMap&) [with BidirectionalGraph = DBGBloom<BloomFilter>; Buffer = boost::queue<Kmer, std::deque<Kmer, std::allocator<Kmer> > >; ColorMap = DefaultColorMap<DBGBloom<BloomFilter> >; typename boost::graph_traits<Graph>::vertex_descriptor = Kmer]'
../Graph/BidirectionalBFS.h:155:18:   required from 'void bidirectionalBFS(const BidirectionalGraph&, typename boost::graph_traits<Graph>::vertex_descriptor, typename boost::graph_traits<Graph>::vertex_descriptor, BidirectionalBFSVisitor<BidirectionalGraph>&) [with BidirectionalGraph = DBGBloom<BloomFilter>; typename boost::graph_traits<Graph>::vertex_descriptor = Kmer]'
konnector.h:314:18:   required from 'ConnectPairsResult connectPairs(unsigned int, const FastaRecord&, const FastaRecord&, const Graph&, const ConnectPairsParams&) [with Graph = DBGBloom<BloomFilter>]'
konnector.cc:740:15:   required from 'void connectPair(const Graph&, const Bloom&, FastqRecord&, FastqRecord&, const ConnectPairsParams&, std::ofstream&, std::ofstream&, std::ofstream&, std::ofstream&) [with Graph = DBGBloom<BloomFilter>; Bloom = BloomFilter; std::ofstream = std::basic_ofstream<char>]'
konnector.cc:903:15:   required from 'void connectPairs(const Graph&, const Bloom&, FastaStream&, const ConnectPairsParams&, std::ofstream&, std::ofstream&, std::ofstream&, std::ofstream&) [with Graph = DBGBloom<BloomFilter>; FastaStream = FastaConcat; Bloom = BloomFilter; std::ofstream = std::basic_ofstream<char>]'
konnector.cc:1203:29:   required from here
/usr/include/boost/graph/graph_concepts.hpp:131:19: error: 'degree' was not declared in this scope
         n = degree(v, g);
             ~~~~~~^~~~~~
```

Boos commit that added `degree()` check: https://github.com/boostorg/graph/commit/50bfd8dad0ded59e3335d7f577549c968b371a80

**Comment by trofi** [comment]
I guess you only need to define `is_directed_graph<G>::type` for that kind of graph.

**Comment by benvvalk** [comment]
Thanks for the bug report, @trofi.

Can you please tell me what compiler/version you are using? (So I will have a way to check that I have successfully fixed it).

**Comment by benvvalk** [comment]
Sorry never mind about the compiler version.  I didn't realize that I just have to upgrade boost to reproduce the error.

**Comment by sjackman** [comment]
Hi, Ben. This issue came up with one of the participants at Hackseq this  weekend.

**Comment by benvvalk** [comment]
Sorry for the trouble, Shaun.  I will fix it and make another release this week.

**Comment by sjackman** [comment]
> Hope someone can help me to fix my installation problem with ABySS. I want to use transabyss 1.5.3 and am having problems to install ABySS 1.5.2. I got the following error during the installation process
…

This issue is caused by some versions of Boost, 1.62.0, and possibly others. Which version of Boost are you using?
@benvvalk Do you know which versions of Boost cause this error?

Try upgrading Boost like so:
```
cd abyss-1.5.2
curl -O http://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2
tar jxf boost_1_56_0.tar.bz2
./configure && make
```

**Comment by benvvalk** [comment]
@sjackman:

Thanks for recognizing this error and redirecting users to this ticket.

This bug occurs when compiling Boost 1.62 or higher is fixed as of release 2.0.2.

If a user specifically wants to an older of ABySS (e.g. 1.5.2), then he/she will have to download the headers for Boost 1.5 and use those when compiling (as per your directions above).

I am closing this ticket as the bug is fixed now.

**Comment by mspiffy** [comment]
Hi Ben, I'm getting the same errors with boost::graph using boost/current in abyss 1.5.2. A work-around of linking against Boost 1.5.0 and 1.5.5 (both tried) did not resolve.
